### ISSUE TITLE
Cannot add checks

### ISSUE THREAD

**Issue by skatt621** [skatt621/Brogrammers#33]
Only checked Firefox and Chrome

![image](https://user-images.githubusercontent.com/37593984/49329725-78a47500-f551-11e8-9ab0-b9b18e63df0d.png)
![image](https://user-images.githubusercontent.com/37593984/49329727-7b06cf00-f551-11e8-9fea-3ad9d33bd249.png)

**Comment by kwetz903** [comment]
fixed, merged, and deployed
